[Build]: Remove display tests result in github actions

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -19,11 +19,11 @@ jobs:
         run: mvn --batch-mode -DskipTests package
       - name: Run unit tests and integration tests
         run: mvn --batch-mode test
-      - name: Display test results
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: Unit Tests results
-          path: target/surefire-reports/*.xml
-          reporter: java-junit
+#      - name: Display test results
+#        uses: dorny/test-reporter@v1
+#        if: success() || failure()
+#        with:
+#          name: Unit Tests results
+#          path: target/surefire-reports/*.xml
+#          reporter: java-junit
 
